### ISSUE TITLE
Use Open Location Code

### ISSUE THREAD

**Issue by pickfire** [apusds/cms#15]
The better is Open Location Code (aka Plus Code).

What3Words are not free. We can also use the alternative WhatFreeWords.

https://whatfreewords.org/faq.html

**Comment by kklee998** [comment]
Please clarify

**Comment by pickfire** [comment]
If the location is just for fun, what 3 words is a good fit, but the bad thing is that what 3 words are bad for developers, people cannot just write what 3 words algorithm with the data and open source it, it will be taken down by DMCA.

**Comment by InspectorGadget** [comment]
@emperorinfinite *ping
