### ISSUE TITLE
image caching & compression

### ISSUE THREAD

**Issue by InspectorGadget** [apusds/cms#3]
- [ ] Compress image
- [x] Multiple upload for Gallery
- [ ] Compress image while uploading (Laravel Background Process)

PS: Should not need to run Linux Command, Laravel has an Image Compressor.

**Comment by kklee998** [comment]
TBD: resizing images in server rather than in HTML

**Comment by pickfire** [comment]
We should also generate thumbnail versions to make it mobile-friendly?

**Comment by InspectorGadget** [comment]
The resize will be done after Almond has redesigned the Gallery, for now it will be pushed to a new branch w/o any compression. That branch will not go live w/o the redesign.
