### ISSUE TITLE
Broken Export on meetup-attendee branch

### ISSUE THREAD

**Issue by kklee998** [apusds/cms#39]
**Describe the bug**
I cant seem to export even though i copied exactly from MemberController

**To Reproduce**
1. Go to 'Meetups'
2. Click on 'Attendees'
3. Click on 'Downloads'

**Expected behavior**
Export and download as "member.csv"

**Screenshots**
Error
![image](https://user-images.githubusercontent.com/23695764/67616642-e6165f80-f80d-11e9-93e1-37b9e916ee6f.png)

Result of $list
![image](https://user-images.githubusercontent.com/23695764/67616685-342b6300-f80e-11e9-9264-feff79c500a5.png)

**Comment by InspectorGadget** [comment]
Will check and fix

**Comment by kklee998** [comment]
Closed on commit 31ed8a7e0ad577077ea0752cef675f38c84973d0
