### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by pickfire** [apusds/cms#46]
**Is your feature request related to a problem? Please describe.**

Entry guide.

**Describe the solution you'd like**

CONTRIBUTING.md https://gist.github.com/PurpleBooth/b24679402957c63ec426 similar to code of conduct

**Describe alternatives you've considered**

Up to maintainers to review and comment.

**Additional context**

None

**Comment by InspectorGadget** [comment]
@kklee998 Can you please have a look?
