### ISSUE TITLE
Consistent design for buttons.

### ISSUE THREAD

**Issue by alavibazam** [apusds/cms#6]
Follow a consistent design and animation for all the buttons in the website.

**Comment by almondheng** [comment]
@alavibazam please provide specific suggestions

**Comment by alavibazam** [comment]
Change the register button to be the same as the join us button, I think same animation will do as well. The register button is not properly visible now. DSC button keep it the same, will maintain that consistency in the DSC page.

**Comment by almondheng** [comment]
@alavibazam The same animation as join us button will result in overlap with the background-color.
